seed: 42

data:
  dataset:        "cifar10"
  img_size:       32
  batch_size:     64
  shuffle_buffer: 10000
  num_classes:    10

federation:
  n_clients:       10
  client_fraction: 0.5
  n_rounds:        50
  partition:       "noniid"   # "iid" or "noniid"
  alpha:           0.3        # Dirichlet alpha, only used when partition=noniid

training:
  local_epochs:   5
  learning_rate:  0.01

wandb:
  enabled:  true
  entity:   "3445339138-kth-royal-institute-of-technology"   # 改成你的 wandb 用户名
  project:  "fedavg-cifar10"
  run_name: "fedavg-noniid-alpha0.3-epoch5-frac0.5"
