wandb_version: 1

batch_size:
  value: 256
depth:
  value: 28
dropout:
  value: 0.1
epochs:
  value: 100
lr:
  value: 0.1923175126634951
lr_schedule:
  value: cosine
use_cutout:
  value: true
warmup_epochs:
  value: 5
weight_decay:
  value: 0.0006869386940728871
width:
  value: 4
