wandb_version: 1

batch_size:
  value: 256
depth:
  value: 28
dropout:
  value: 0
epochs:
  value: 100
lr:
  value: 0.0888039737717535
lr_schedule:
  value: cosine
use_cutout:
  value: true
warmup_epochs:
  value: 5
weight_decay:
  value: 0.0003078061070172659
width:
  value: 4
