wandb_version: 1

batch_size:
  value: 256
depth:
  value: 28
dropout:
  value: 0.1
epochs:
  value: 200
lr:
  value: 0.07553840716992306
lr_schedule:
  value: multistep
use_cutout:
  value: true
warmup_epochs:
  value: 5
weight_decay:
  value: 0.0006624001768109541
width:
  value: 6
