wandb_version: 1

batch_size:
  value: 128
depth:
  value: 28
dropout:
  value: 0.1
epochs:
  value: 200
lr:
  value: 0.18430490945190744
lr_schedule:
  value: multistep
use_cutout:
  value: true
warmup_epochs:
  value: 5
weight_decay:
  value: 0.00011498917581299768
width:
  value: 4
