seed: 42
data:
  dataset:        "cifar100"
  img_size:       32
  batch_size:     16
  shuffle_buffer: 10000
  num_classes:    100

federation:
  edge_assignment:  "semantic"
  client_fraction:  1.0
  warmup_rounds:    5
  n_clients:        100
  n_edges:          2
  edge_rounds:      5
  n_rounds:         200
  partition:        "pathological"
  alpha:            0.1

training:
  local_epochs:   5
  learning_rate:  0.02
  lr_decay:       0.992
  drift_correction: "hierpfedme"
  proximal_ref:     "edge"
  mu:               1.0
  mu_edge:          0.1
  mu_global:        0.01
  alpha_feddyn:     0.1
  alpha_feddyn_global: 0.02
  lambda_pfedme:    35.0
  beta_pfedme:      1.0
  pfedme_warm_start: false
  lambda1_hier:     35.0
  lambda2_hier:     35.0
  beta_hier:        1.0
  inner_steps_hier: 1
  alpha_inner:      0.01

model:
  arch: "cifar_cnn_3conv"

wandb:
  enabled:  true
  entity:   "3445339138-kth-royal-institute-of-technology"
  project:  "HierFL-cifar100"
  # run_name: "H4_hierpfedme_c100_localepoch_5_random_dirichet_alpha_0.1"
  run_name: "I1_hierpfedme_c100_localepoch_5_semantic_pathological"

evaluation:
  eval_interval: 10