_wandb:
    value:
        cli_version: 0.25.1
        e:
            nxeg5z55gqj15cnddfdb5iq721en7tkd:
                args:
                    - --config
                    - config/config.yaml
                    - --override
                    - wandb.enabled=true
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "18843648000"
                        used: "12653678592"
                email: 3445339138@qq.com
                executable: /cephyr/users/ziangg/Alvis/TF_DPFL_2026/bin/python
                gpu: NVIDIA A40
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-8ccd13fe-987c-aa9c-5859-d787826fe4a7
                host: alvis6-08
                memory:
                    total: "269549350912"
                os: Linux-4.18.0-553.109.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /cephyr/users/ziangg/Alvis/tf-dpfl/fedavg/main.py
                python: CPython 3.11.3
                root: /cephyr/users/ziangg/Alvis/tf-dpfl/fedavg
                slurm:
                    cluster_name: alvis
                    conf: /tmp/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "16"
                    gpus_on_node: "1"
                    gpus_per_node: A40:1
                    gtids: "0"
                    job_account: naiss2026-4-650
                    job_cpus_per_node: "16"
                    job_end_time: "1775696527"
                    job_gid: "10225343"
                    job_gpus: "1"
                    job_id: "6356465"
                    job_name: HierFLcifar10
                    job_nodelist: alvis6-08
                    job_num_nodes: "1"
                    job_partition: alvis
                    job_qos: normal
                    job_start_time: "1775610127"
                    job_uid: "10225343"
                    job_user: ziangg
                    jobid: "6356465"
                    localid: "0"
                    mem_per_node: "62496"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: alvis6-08
                    oom_kill_step: "0"
                    pmix_direct_conn_ucx: "false"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /cephyr/users/ziangg/Alvis
                    submit_host: alvis1
                    task_pid: "315876"
                    tasks_per_node: "1"
                    topology_addr: eth-root.eth-sw06.alvis6-08
                    topology_addr_pattern: switch.switch.node
                startedAt: "2026-04-08T01:03:08.012258Z"
                writerId: nxeg5z55gqj15cnddfdb5iq721en7tkd
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.3
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
data:
    value:
        batch_size: 256
        dataset: cifar10
        img_size: 32
        num_classes: 10
        shuffle_buffer: 10000
federation:
    value:
        alpha: 0.5
        client_fraction: 0.2
        edge_rounds: 5
        n_clients: 50
        n_edges: 2
        n_rounds: 10
        partition: noniid
model:
    value:
        arch: wideresnet28_4
seed:
    value: 42
training:
    value:
        learning_rate: 0.01
        local_epochs: 6
        lr_decay: 0.992
wandb:
    value:
        enabled: true
        entity: 3445339138-kth-royal-institute-of-technology
        project: HierFL-cifar10
        run_name: HierWRN164_client=20_edge=2_rounds=10_edge rounds=5_localepoch=6_0.5_frac=0.5
